version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_NAME: qp_assesment # Ensure this matches the database name
      DB_USER: root
      DB_PASSWORD: Shweta@1234
      DB_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "3000:3000"
  
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Shweta@1234
      MYSQL_DATABASE: qp_assesment # This should be qp_assessment, not qp_assesment
    ports:
      - "3306:3306"
